language: node_js
node_js:
  - '0.10'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y php5
  - sudo apt-get install -y ruby-full
  - sudo apt-get install -y libgemplugin-ruby
  - sudo gem install compass
  - npm install -g grunt-cli
