sudo: false
language: php
node_js:
  - '5.6'
before_install:
  - composer self-update
  - npm install -g grunt-cli
  - npm --version
  - node --version
  - npm cache clean -f
  - npm install -g n
  - n stable
  - npm --version
  - node --version
install:
  - npm install
script:
  - grunt builddist
  - npm test
