sudo: false
language: php
node_js:
  - '5.6'
before_install:
  - composer self-update
  - nvm install 4.2.4
  - nvm use 4.2.4
  - npm install -g grunt-cli
  - npm --version
  - node --version
install:
  - npm install
script:
  - npm test
